# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_xXTxZad8gFOHbgEqvjly7EeqCJZ3Wz
"""

import cv2
import matplotlib.pyplot as plt

# Step 1: Load the image
# Provide the path to your image file
image_path = 'input_image.jpg'
image = cv2.imread(image_path)

# Check if the image is loaded successfully
if image is None:
    raise FileNotFoundError(f"Image file '{image_path}' not found. Please provide a valid path.")

# Step 2: Display the original image (in RGB format for matplotlib)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title("Original Image")
plt.axis("off")
plt.show()

# Step 3: Convert the image to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Step 4: Resize the image (example: half the original size)
height, width = gray_image.shape
new_size = (width // 2, height // 2)
resized_image = cv2.resize(gray_image, new_size)

# Step 5: Display the grayscale resized image
plt.imshow(resized_image, cmap='gray')
plt.title("Grayscale Resized Image")
plt.axis("off")
plt.show()

# Step 6: Save the processed image to disk
output_path = 'processed_image.jpg'
cv2.imwrite(output_path, resized_image)
print(f"Processed image saved as '{output_path}'")

# Step 7: Optional – Basic interaction example
name = input("Enter your name: ")
print(f"Hello, {name}! Your image has been processed successfully.")

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload original image
image_path = 'input_image.jpg'

# The 'uploaded' variable is expected to be a dictionary returned by files.upload().
# Ensure files.upload() is run before this cell to populate 'uploaded'.
# Example: uploaded = files.upload()

# The previous error occurred because 'uploaded' was not defined.
# If you intend to upload a new file, you would typically run `uploaded = files.upload()` first.
# Since 'input_image.jpg' is already available, we will directly load it.
img = cv2.imread(image_path)

# Auto contrast/brightness

def auto_brightness_contrast(image, clip_hist_percent=25):
    # All lines below this function definition must be indented
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    hist = cv2.calcHist([gray],[0],None,[256],[0,256]).flatten()
    acc = np.cumsum(hist)
    clip = clip_hist_percent * (acc[-1] / 100.0) / 2.0
    min_gray = np.searchsorted(acc, clip)
    max_gray = np.searchsorted(acc, acc[-1] - clip)
    alpha = 255 / (max_gray - min_gray + 1e-5)
    beta = -min_gray * alpha
    return cv2.convertScaleAbs(image, alpha=alpha, beta=beta)

enhanced = auto_brightness_contrast(img)
resized = cv2.resize(enhanced, (1080, 1080))

# Show before and after
fig, ax = plt.subplots(1, 2, figsize=(12, 5))
ax[0].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
ax[0].set_title("Original")
ax[1].imshow(cv2.cvtColor(resized, cv2.COLOR_BGR2RGB))
ax[1].set_title("Enhanced & Resized")
for a in ax: a.axis('off')
plt.tight_layout()
plt.show()

import cv2
import numpy as np
from google.colab import files
import matplotlib.pyplot as plt
from skimage.metrics import structural_similarity as ssim
# Upload two images
print("Please upload two images for comparison.")
uploaded = files.upload()

# Removed stray '19' that was causing a syntax error.

paths = list(uploaded.keys())

if len(paths) < 2:
    print("Error: Please upload at least two images to perform comparison.")
else:
    # Read and resize
    img1 = cv2.imread(paths[0])
    img2 = cv2.imread(paths[1])

    img1 = cv2.resize(img1, (500, 500))
    img2 = cv2.resize(img2, (500, 500))

    gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
    gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

    # MSE and SSIM
    mse = np.mean((gray1 - gray2) ** 2)
    ssim_score, _ = ssim(gray1, gray2, full=True)

    print(f"MSE: {mse:.2f}")
    print(f"SSIM: {ssim_score:.4f}")

    # Show both images
    fig, ax = plt.subplots(1, 2, figsize=(10, 4))
    ax[0].imshow(cv2.cvtColor(img1, cv2.COLOR_BGR2RGB))
    ax[0].set_title("Image 1")
    ax[1].imshow(cv2.cvtColor(img2, cv2.COLOR_BGR2RGB))
    ax[1].set_title("Image 2")
    for a in ax: a.axis('off')
    plt.show()